// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace IntelliCRMAPIService.DBContext
{
    public class OrdersProducts
    {
        public long OrderProductId { get; set; }
        public long OrdersID { get; set; }
        public int Productid { get; set; }
        public string Equsbrandname { get; set; }
        public string Category { get; set; }
        public string Nameonpackage { get; set; }
        public string Strength { get; set; }
        public string Unitsperpack { get; set; }
        public int Quantity { get; set; }
        public string Dosageform { get; set; }
        public string Activeingredients { get; set; }
        public string Productsourcedfrom { get; set; }
        public string Totalpacksordered { get; set; }
        public string Totalpricecustomerpays { get; set; }
        public string Priceperpackclientpays { get; set; }
        public string Shippingcostperorder { get; set; }
        public string Totalpriceclientpays { get; set; }
        public string Createdby { get; set; }
        public DateTime? Createddate { get; set; } = default(DateTime?);
        public string? Modifiedby { get; set; }
        public DateTime? Modifieddate { get; set; }
    }
}