// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IntelliCRMAPIService.DBContext
{
    public partial class Orders 
    {
        public long Ordersid { get; set; }
        public DateTime? Date { get; set; }
        public string Referencenumber { get; set; }
        public string OnlinepharmacyName { get; set; }
        public string Onlinepharmacy { get; set; }
        public string Onlinepharmacyphonenumber { get; set; }
        public string Ordernumber { get; set; }
        public string Customername { get; set; }
        public string DoctorName { get; set; }
        public string Refill { get; set; }
        public string Customerphonenumber { get; set; }
        public string Emailaddress { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Zipcode { get; set; }
        public string Prescribername { get; set; }
        public string Prescriptionattached { get; set; }
        public string Directionsofuse { get; set; }
        public string Rxwarningcautionarynote { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string Createdby { get; set; }
        public DateTime? Createddate { get; set; } = default(DateTime?);
        public string? Modifiedby { get; set; }
        public DateTime? Modifieddate { get; set; }
    }
}